server:
  port: 8079

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/tdd?useSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: bd3cf1rzh.
    schema: classpath*:db/schema-mysql.sql
    data: classpath*:db/data.sql
