DROP SCHEMA IF EXISTS TTD;
CREATE SCHEMA TTD;
USE TTD;

DROP TABLE IF EXISTS ums_admin;
CREATE TABLE ums_admin (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  username varchar(64) DEFAULT NULL,
  password varchar(64) DEFAULT NULL,
  icon varchar(500) DEFAULT NULL COMMENT '头像',
  email varchar(100) DEFAULT NULL COMMENT '邮箱',
  nick_name varchar(200) DEFAULT NULL COMMENT '昵称',
  note varchar(500) DEFAULT NULL COMMENT '备注信息',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  login_time datetime DEFAULT NULL COMMENT '最后登录时间',
  status int(1) DEFAULT '1' COMMENT '帐号启用状态：0->禁用；1->启用',
  PRIMARY KEY (id)
) COMMENT='后台用户表';

DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
  USER_ID bigint(20) NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(40) NOT NULL COMMENT '用户名',
  PASSWORD_ENCRYPTED varchar(80) DEFAULT NULL COMMENT '加密过的密码',
  EMAIL varchar(150) DEFAULT NULL COMMENT '邮箱地址',
  PHONE varchar(40) DEFAULT NULL COMMENT '电话号码',
  START_ACTIVE_DATE datetime DEFAULT NULL COMMENT '有效期从',
  END_ACTIVE_DATE datetime DEFAULT NULL COMMENT '有效期至',
  STATUS varchar(30) DEFAULT NULL COMMENT '状态',
  DESCRIPTION varchar(255) DEFAULT NULL COMMENT '说明',
  PRIMARY KEY (USER_ID),
  UNIQUE KEY SYS_USER_U1 (USER_NAME)
) COMMENT='用户表';