DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '主键',
    `NAME` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '姓名',
    `ADDRESS` VARCHAR(255) DEFAULT '' NOT NULL COMMENT '地址',
    `ID_CARD` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '身份证',
    `BANK_CARD` VARCHAR(50) DEFAULT '' NOT NULL COMMENT '银行卡',
    `VERIFY_STATUS` SMALLINT DEFAULT 0 NOT NULL COMMENT '审核状态'
) DEFAULT CHARSET=utf8mb4 COMMENT '作者信息表';