server:
  port: 8079
  max-http-header-size: 1024

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:~/test
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: sa
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    initialization-mode: embedded

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true

logging:
  level:
    root: debug
    org:
      apache:
        tomcat:
          util: error